apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      replicas: 1
      containers:
      - name: redis-deploy
        labels:
          name: result-app-pod
          app: demo-voting-app
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
