apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
spec:
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      replicas: 1
      containers:
      - name: worker-app-deploy
        image: kodekloud/examplevotingapp_worker:V1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
